#!/usr/bin/env sh
set -eu

root_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$root_dir"

echo "== Interface audit =="

status=0

check_no_constructors() {
  name=$1
  path=$2

  if ! rg -q "^inductive ${name}\\b" "$path"; then
    echo "FAIL: $name is not declared in $path"
    status=1
    return
  fi

  constructors=$(
    awk -v name="$name" '
      $0 ~ "^inductive " name "([[:space:]]|$)" { in_decl = 1; next }
      in_decl && $0 ~ /^[[:space:]]*$/ { in_decl = 0 }
      in_decl && $0 ~ /^[[:space:]]*\|/ { print }
    ' "$path"
  )

  if [ -n "$constructors" ]; then
    echo "FAIL: $name has local constructors in $path"
    printf '%s\n' "$constructors"
    status=1
  else
    echo "PASS: $name has no local constructors"
  fi
}

check_no_constructors "IsRicciTensorOf" "Poincare/RicciFlow.lean"
check_no_constructors "SatisfiesRicciFlowEquation" "Poincare/RicciFlow.lean"
check_no_constructors "HasLeviCivitaConnectionTheory" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasLeviCivitaConnectionExistence" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasLeviCivitaConnectionUniqueness" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasLeviCivitaTorsionFreeProperty" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasLeviCivitaMetricCompatibility" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasRiemannCurvatureTensorTheory" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasRiemannCurvatureTensorConstruction" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasRiemannCurvatureTensorSymmetries" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasFirstBianchiIdentity" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasSecondBianchiIdentity" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasRicciContractionTheory" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasRicciTensorContractionFormula" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasScalarCurvatureContractionFormula" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasTimeDependentMetricRegularity" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasMetricTimeDerivativeTheory" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasScalarCurvatureTheory" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasRicciFlowEquationDerivation" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasInitialMetricCompatibility" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasDeTurckGaugeFixing" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasDeTurckBackgroundMetricCompatibility" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasDeTurckVectorFieldConstruction" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasDeTurckEquationDerivation" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasRicciDeTurckLinearization" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasStrictlyParabolicDeTurckSystem" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasParabolicLinearTheory" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasParabolicFixedPointArgument" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasDeTurckShortTimeExistence" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasShortTimeRegularityBootstrap" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasDeTurckDiffeomorphismODE" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasDeTurckPullbackEquationIdentity" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasDeTurckPullbackToRicciFlow" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasShortTimeRicciFlowSolution" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasRicciFlowMaximalTimeInterval" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasRicciFlowContinuationCriterion" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasCurvatureBlowUpContinuationCriterion" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasMaximalSolutionExtension" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasParabolicSchauderEstimates" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasRicciFlowParabolicRegularity" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasShiDerivativeEstimates" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasCurvatureDerivativeBootstrap" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasHamiltonMaximumPrinciple" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasRicciFlowUniquenessTheory" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasMetricEvolutionEquation" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasRicciTensorEvolutionEquation" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasScalarCurvatureEvolutionEquation" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasCurvatureNormEvolutionInequality" "Poincare/AnalyticFoundation.lean"
check_no_constructors "HasCurvatureEvolutionEquations" "Poincare/AnalyticFoundation.lean"
check_no_constructors "FiniteExtinctionByRicciFlowWithSurgery" "Poincare/RicciFlowInterface.lean"
check_no_constructors "HasRicciFlowWithSurgery" "Poincare/Surgery.lean"
check_no_constructors "HasSurgeryParameterSelection" "Poincare/Surgery.lean"
check_no_constructors "HasSurgeryScaleFunction" "Poincare/Surgery.lean"
check_no_constructors "HasSurgeryScaleContinuity" "Poincare/Surgery.lean"
check_no_constructors "HasSurgeryScaleSeparation" "Poincare/Surgery.lean"
check_no_constructors "HasSurgeryCutoffParameterControl" "Poincare/Surgery.lean"
check_no_constructors "HasSurgeryCutoffSmoothBumpFunction" "Poincare/Surgery.lean"
check_no_constructors "HasSurgeryNeckDecomposition" "Poincare/Surgery.lean"
check_no_constructors "HasStrongDeltaNeckDetection" "Poincare/Surgery.lean"
check_no_constructors "HasSurgeryNeckSeparation" "Poincare/Surgery.lean"
check_no_constructors "HasSurgeryNeckParametrization" "Poincare/Surgery.lean"
check_no_constructors "HasSurgeryNeckCanonicalCoordinates" "Poincare/Surgery.lean"
check_no_constructors "HasSurgeryCapConstruction" "Poincare/Surgery.lean"
check_no_constructors "HasStandardCapModel" "Poincare/Surgery.lean"
check_no_constructors "HasCapGluingSmoothness" "Poincare/Surgery.lean"
check_no_constructors "HasSurgeryCapMetricInterpolation" "Poincare/Surgery.lean"
check_no_constructors "HasSurgeryCapCurvatureEstimates" "Poincare/Surgery.lean"
check_no_constructors "HasPostSurgeryMetricControl" "Poincare/Surgery.lean"
check_no_constructors "HasPostSurgeryCurvaturePinching" "Poincare/Surgery.lean"
check_no_constructors "HasPostSurgeryNoncollapsingControl" "Poincare/Surgery.lean"
check_no_constructors "HasPostSurgeryDerivativeBounds" "Poincare/Surgery.lean"
check_no_constructors "HasPostSurgeryCanonicalNeighborhoodPersistence" "Poincare/Surgery.lean"
check_no_constructors "HasLongTimeSurgeryContinuation" "Poincare/Surgery.lean"
check_no_constructors "HasSurgeryTimeDiscreteness" "Poincare/Surgery.lean"
check_no_constructors "HasSurgeryTimeLocalFiniteness" "Poincare/Surgery.lean"
check_no_constructors "HasLongTimeExistenceIteration" "Poincare/Surgery.lean"
check_no_constructors "HasLongTimeSurgeryParameterCoherence" "Poincare/Surgery.lean"
check_no_constructors "HasLongTimeNonaccumulation" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanSingularityControl" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanEntropyFunctional" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanFFunctionalSetup" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanEntropyNormalization" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanEntropyMinimizerExistence" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanEntropyLogSobolevControl" "Poincare/Surgery.lean"
check_no_constructors "HasConjugateHeatEquationTheory" "Poincare/Surgery.lean"
check_no_constructors "HasAdjointHeatKernelConstruction" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanConjugateHeatKernelEstimates" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanWFunctionalSetup" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanEntropyGradientFormula" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanEntropyFirstVariation" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanEntropyMonotonicity" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanEntropyLowerBoundPropagation" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanReducedDistanceTheory" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanReducedLengthFirstVariation" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanReducedDistanceExistence" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanReducedDistanceDifferentialInequality" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanReducedDistanceEstimates" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanReducedDistanceCutLocusControl" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanReducedJacobianComparison" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanReducedVolumeNonincreasing" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanReducedVolumeDefinition" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanReducedVolumeDerivativeFormula" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanReducedVolumeRigidity" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanReducedVolumePositiveLowerBound" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanReducedVolumeLimitRigidity" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanKappaNoncollapsingQuantification" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanNoLocalCollapsingContradictionSetup" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanCollapsedBallBlowup" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanVolumeRatioContradiction" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanKappaNoncollapsingFromReducedVolume" "Poincare/Surgery.lean"
check_no_constructors "HasNoLocalCollapsingVolumeLowerBound" "Poincare/Surgery.lean"
check_no_constructors "HasHamiltonCompactnessTheorem" "Poincare/Surgery.lean"
check_no_constructors "HasAncientKappaSolutionCompactness" "Poincare/Surgery.lean"
check_no_constructors "HasAncientKappaSolutionLimitExtraction" "Poincare/Surgery.lean"
check_no_constructors "HasKappaSolutionPointedRescaling" "Poincare/Surgery.lean"
check_no_constructors "HasKappaSolutionCurvatureNormalization" "Poincare/Surgery.lean"
check_no_constructors "HasKappaSolutionStructureTheory" "Poincare/Surgery.lean"
check_no_constructors "HasKappaSolutionNonnegativeCurvatureOperator" "Poincare/Surgery.lean"
check_no_constructors "HasKappaSolutionAsymptoticSoliton" "Poincare/Surgery.lean"
check_no_constructors "HasCanonicalNeighborhoodClassification" "Poincare/Surgery.lean"
check_no_constructors "HasCanonicalNeighborhoodNeckCapDichotomy" "Poincare/Surgery.lean"
check_no_constructors "HasCanonicalNeighborhoodScaleControl" "Poincare/Surgery.lean"
check_no_constructors "HasCanonicalNeighborhoodStability" "Poincare/Surgery.lean"
check_no_constructors "HasCanonicalNeighborhoodPersistenceAcrossScales" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanNoLocalCollapsing" "Poincare/Surgery.lean"
check_no_constructors "HasPerelmanReducedVolumeMonotonicity" "Poincare/Surgery.lean"
check_no_constructors "HasCanonicalNeighborhoodTheorem" "Poincare/Surgery.lean"
check_no_constructors "HasSingularityModelClassification" "Poincare/Surgery.lean"
check_no_constructors "HasSingularityModelBlowupClassification" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionFundamentalGroupInput" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionSweepoutExistence" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionSweepoutParameterSpace" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionSweepoutContinuity" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionSweepoutAreaBound" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionSweepoutNontriviality" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionAreaFunctionalSetup" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionMinMaxWidthDefinition" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionWidthCompactness" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionWidthLowerSemicontinuity" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionMinimizingSequence" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionPullTightArgument" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionMinMaxStationarity" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionMinSurfaceRegularity" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionPositiveWidth" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionWidthTheory" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionFirstVariationFormula" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionSecondVariationInequality" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionGaussBonnetEstimate" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionScalarCurvatureWidthBound" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionWidthEvolution" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionWidthDifferentialInequality" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionSurgeryMetricComparison" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionSurgeryWidthComparisonMap" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionSurgeryWidthDrop" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionSurgeryDiscardControl" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionDiscardedComponentWidthNeutrality" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionDiscardedComponentSweepoutTriviality" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionDiscardedComponentClassification" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionSurvivingComponentTracking" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionComponentTopology" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionDerivation" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionCurvaturePinching" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionPositiveScalarCurvatureLowerBound" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionPositiveScalarCurvaturePersistence" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionComponentControl" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionVolumeEvolutionFormula" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionSurgeryVolumeNonincrease" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionScalarCurvatureDifferentialInequality" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionVolumeDifferentialInequality" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionVolumeDecayEstimate" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionTimeBound" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionDifferentialInequalityIntegration" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionFiniteTimeIntegration" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionSurgeryTimeSummability" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionExtinctionTimeContradiction" "Poincare/Surgery.lean"
check_no_constructors "HasFiniteExtinctionConclusionDerivation" "Poincare/Surgery.lean"
check_no_constructors "HasExtinctionTopologyDecomposition" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionSurgeryTraceReconstruction" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionSurgeryTraceHandleCancellation" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionComponentClassification" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionDiscardedComponentHomeomorphismClassification" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionComponentInventory" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionComponentBoundarySphereControl" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasThreeSphereRecognition" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionPrimeDecomposition" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionPrimeDecompositionExistence" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionSphereTheoremApplication" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionEmbeddedSphereProduction" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionLoopTheoremApplication" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionPrimeDecompositionCompatibility" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionPrimeFactorUniqueness" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionIrreducibility" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionIrreducibleFactorRecognition" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionConnectedSumCollapse" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionConnectedSumFundamentalGroupControl" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionConnectedSumVanKampenCalculation" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionSimplyConnectedPrimeFactorControl" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionSphericalSpaceFormReduction" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasSphericalSpaceFormClassification" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasSphericalSpaceFormQuotientModel" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasSphericalSpaceFormFreeAction" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasSphericalSpaceFormUniversalCover" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasSphericalSpaceFormCoveringModel" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasSphericalSpaceFormCoveringProjection" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasSphericalSpaceFormFundamentalGroupComputation" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasSphericalSpaceFormDeckGroupIdentification" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasSphericalSpaceFormDeckActionProperness" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasSphericalSpaceFormDeckGroupTriviality" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasSphericalSpaceFormDeckActionTrivialization" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasSphericalSpaceFormTrivialDeckQuotientIdentification" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasSimplyConnectedExtinctionRecognition" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasTrivialSphericalSpaceFormQuotient" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasSphericalSpaceFormTrivialQuotientHomeomorphism" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasSphericalSpaceFormHomeomorphismLift" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionHomeomorphismAssembly" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasExtinctionHomeomorphismDerivation" "Poincare/TopologyExtraction.lean"
check_no_constructors "HasMoiseTriangulation" "Poincare/Smoothability.lean"
check_no_constructors "HasMoiseLocalTriangulationCharts" "Poincare/Smoothability.lean"
check_no_constructors "HasMoiseLocallyFiniteCoverRefinement" "Poincare/Smoothability.lean"
check_no_constructors "HasMoiseSimplicialComplex" "Poincare/Smoothability.lean"
check_no_constructors "HasMoiseCompatibleChartTriangulations" "Poincare/Smoothability.lean"
check_no_constructors "HasMoiseSimplicialApproximation" "Poincare/Smoothability.lean"
check_no_constructors "HasMoiseStarNeighborhoodBasis" "Poincare/Smoothability.lean"
check_no_constructors "HasMoiseBarycentricSubdivisionControl" "Poincare/Smoothability.lean"
check_no_constructors "HasMoiseRegularNeighborhoodCompatibility" "Poincare/Smoothability.lean"
check_no_constructors "HasMoiseTriangulationLocalFiniteness" "Poincare/Smoothability.lean"
check_no_constructors "HasMoiseLinkCompatibility" "Poincare/Smoothability.lean"
check_no_constructors "HasMoisePLManifoldRecognition" "Poincare/Smoothability.lean"
check_no_constructors "HasMoiseTriangulationHomeomorphism" "Poincare/Smoothability.lean"
check_no_constructors "HasMoiseTriangulationCompatibility" "Poincare/Smoothability.lean"
check_no_constructors "HasMoiseTriangulationUniqueness" "Poincare/Smoothability.lean"
check_no_constructors "HasMoiseHauptvermutungDimensionThree" "Poincare/Smoothability.lean"
check_no_constructors "HasCompatiblePLStructure" "Poincare/Smoothability.lean"
check_no_constructors "HasPLTransitionCompatibility" "Poincare/Smoothability.lean"
check_no_constructors "HasCompatiblePLAtlas" "Poincare/Smoothability.lean"
check_no_constructors "HasPLManifoldAtlas" "Poincare/Smoothability.lean"
check_no_constructors "HasPLCollarNeighborhoodCompatibility" "Poincare/Smoothability.lean"
check_no_constructors "HasPLHomeomorphismCompatibility" "Poincare/Smoothability.lean"
check_no_constructors "HasPLAtlasMaximality" "Poincare/Smoothability.lean"
check_no_constructors "HasPLSmoothingExistence" "Poincare/Smoothability.lean"
check_no_constructors "HasPLSmoothingObstructionVanishing" "Poincare/Smoothability.lean"
check_no_constructors "HasPLMicrobundleSmoothing" "Poincare/Smoothability.lean"
check_no_constructors "HasPLSmoothingTheorem" "Poincare/Smoothability.lean"
check_no_constructors "HasPLSmoothingCompatibility" "Poincare/Smoothability.lean"
check_no_constructors "HasPLSmoothingUniqueness" "Poincare/Smoothability.lean"
check_no_constructors "HasPLSmoothingLocalModelCompatibility" "Poincare/Smoothability.lean"
check_no_constructors "HasThreeManifoldSmoothStructure" "Poincare/Smoothability.lean"
check_no_constructors "HasSmoothAtlasConstruction" "Poincare/Smoothability.lean"
check_no_constructors "HasSmoothAtlasPLCompatibility" "Poincare/Smoothability.lean"
check_no_constructors "HasSmoothAtlasMaximality" "Poincare/Smoothability.lean"
check_no_constructors "HasSmoothAtlasUniqueness" "Poincare/Smoothability.lean"
check_no_constructors "HasSmoothStructureUniquenessUpToDiffeomorphism" "Poincare/Smoothability.lean"
check_no_constructors "HasSmoothTransitionCompatibility" "Poincare/Smoothability.lean"
check_no_constructors "HasSmoothAtlasTransitionSmoothness" "Poincare/Smoothability.lean"
check_no_constructors "HasSmoothStructureDerivation" "Poincare/Smoothability.lean"
check_no_constructors "HasSmoothabilityBridgeDerivation" "Poincare/Smoothability.lean"
check_no_constructors "HasSmoothManifoldModelCompatibility" "Poincare/Smoothability.lean"
check_no_constructors "HasSmoothChartCompatibility" "Poincare/Smoothability.lean"

if [ "$status" -eq 0 ]; then
  echo "INTERFACES: no local constructors detected for gap-bearing predicates"
else
  echo "INTERFACES: weakened interface detected"
fi

exit "$status"
