#!/usr/bin/env sh
set -eu

root_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$root_dir"

# Portable fallback: use the bundled Python ripgrep subset only when no `rg`
# binary is on PATH (see scripts/bin/rg).
if ! command -v rg >/dev/null 2>&1; then
  PATH="$root_dir/scripts/bin:$PATH"
  export PATH
fi

out="CURRENT_STATUS.md"
tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/poincare-status.$$-XXXXXX")
tmp="$tmp_dir/CURRENT_STATUS.md"
generated_at=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
toolchain=$(tr -d '\n' < lean-toolchain)

cleanup() {
  rm -rf "$tmp_dir"
}

trap cleanup EXIT

# Lake otherwise honors override variables that can select another installation
# even with a pinned PATH. Normalize them before both capture and execution.
unset LAKE_OVERRIDE_LEAN LAKE_OVERRIDE_LAKE LEAN_SYSROOT LEAN LEAN_PATH LEAN_SRC_PATH
python3 scripts/verification_receipts.py snapshot --out "$tmp_dir/source-before.json"
# Every fresh gate and its children execute the binaries bound by the receipt.
# This avoids an ambient PATH wrapper selecting a different Lean/Lake install.
toolchain_bin=$(python3 scripts/verification_receipts.py toolchain-path \
  --snapshot "$tmp_dir/source-before.json")
PATH="$toolchain_bin:$PATH"
export PATH

run_capture() {
  label=$1
  shift
  python3 scripts/verification_receipts.py run-phase \
    --label "$label" --phase-dir "$tmp_dir" -- "$@"
}

run_capture build lake build
build_status=$(cat "$tmp_dir/build.status")

run_capture interface sh scripts/interface_audit.sh
interface_status=$(cat "$tmp_dir/interface.status")

run_capture mathlib sh scripts/mathlib_gap_audit.sh
mathlib_status=$(cat "$tmp_dir/mathlib.status")

run_capture shape sh scripts/shape_contract_audit.sh
shape_status=$(cat "$tmp_dir/shape.status")

run_capture theorem sh scripts/theorem_contract_audit.sh
theorem_status=$(cat "$tmp_dir/theorem.status")

run_capture semantic sh scripts/semantic_surface_audit.sh
semantic_status=$(cat "$tmp_dir/semantic.status")

run_capture root_import sh scripts/root_import_audit.sh
root_import_status=$(cat "$tmp_dir/root_import.status")

run_capture axiom sh scripts/axiom_audit.sh
axiom_status=$(cat "$tmp_dir/axiom.status")

run_capture completion env COMPLETION_AUDIT_SKIP_STATUS_SNAPSHOT=1 \
  COMPLETION_AUDIT_GATE_RESULTS_DIR="$tmp_dir" sh scripts/completion_audit.sh
completion_status=$(cat "$tmp_dir/completion.status")

completion_result="not achieved"
if rg -q '^COMPLETION: achieved$' "$tmp_dir/completion.out"; then
  completion_result="achieved"
fi

completion_boundary_status="unknown"
completion_failures="$tmp_dir/completion.failures"
completion_boundary_failures="$tmp_dir/completion.boundary.failures"
rg '^FAIL:' "$tmp_dir/completion.out" > "$completion_failures" || true
rg -v '^FAIL: generated status snapshot does not record the current scaffold/completion/boundary state$|^FAIL: generated status snapshot is missing one or more scaffold/completion audit evidence sections$|^FAIL: generated status snapshot is missing sentinel output from one or more scaffold/completion audit sections$' \
  "$completion_failures" > "$completion_boundary_failures" || true
if [ "$completion_result" = "achieved" ]; then
  completion_boundary_status="proved"
elif [ "$completion_status" = "1" ] &&
    [ "$(wc -l < "$completion_boundary_failures" | tr -d ' ')" = "2" ] &&
    rg -q '^FAIL: local reserved theorem name poincare_conjecture is absent$' "$completion_boundary_failures" &&
    rg -q '^FAIL: Lean cannot confirm Poincare\.poincare_conjecture : PoincareConjectureStatement$' "$completion_boundary_failures"; then
  completion_boundary_status="reserved theorem absent only"
else
  completion_boundary_status="unexpected completion audit failures"
fi

cat > "$tmp" <<EOF
# Current Poincare Formalization Status

This file is generated by \`scripts/write_status_summary.sh\`.

## Result

- Completion: ${completion_result}
- Generated at: ${generated_at}
- Lean toolchain: ${toolchain}
- Build status: ${build_status}
- Interface audit status: ${interface_status}
- Mathlib gap audit status: ${mathlib_status}
- Shape contract audit status: ${shape_status}
- Theorem contract audit status: ${theorem_status}
- Semantic surface audit status: ${semantic_status}
- Root import audit status: ${root_import_status}
- Axiom footprint audit status: ${axiom_status}
- Completion audit status: ${completion_status}
- Completion boundary status: ${completion_boundary_status}
EOF

write_section() {
  title=$1
  output_file=$2
  status_file=$3

  cat >> "$tmp" <<EOF

## ${title}

Status: $(cat "$status_file")

\`\`\`text
EOF
  line_count=$(wc -l < "$output_file" | tr -d ' ')
  if [ "$line_count" -le 80 ]; then
    cat "$output_file" >> "$tmp"
  else
    sed -n '1,40p' "$output_file" >> "$tmp"
    printf '\n... omitted %s middle lines ...\n\n' "$((line_count - 80))" >> "$tmp"
    tail -n 40 "$output_file" >> "$tmp"
  fi
  cat >> "$tmp" <<EOF
\`\`\`
EOF
}

write_section "Build" "$tmp_dir/build.out" "$tmp_dir/build.status"
write_section "Interface Audit" "$tmp_dir/interface.out" "$tmp_dir/interface.status"
write_section "Mathlib Gap Audit" "$tmp_dir/mathlib.out" "$tmp_dir/mathlib.status"
write_section "Shape Contract Audit" "$tmp_dir/shape.out" "$tmp_dir/shape.status"
write_section "Theorem Contract Audit" "$tmp_dir/theorem.out" "$tmp_dir/theorem.status"
write_section "Semantic Surface Audit" "$tmp_dir/semantic.out" "$tmp_dir/semantic.status"
write_section "Root Import Audit" "$tmp_dir/root_import.out" "$tmp_dir/root_import.status"
write_section "Axiom Footprint Audit" "$tmp_dir/axiom.out" "$tmp_dir/axiom.status"
write_section "Completion Audit" "$tmp_dir/completion.out" "$tmp_dir/completion.status"

cat >> "$tmp" <<EOF

## Phase Durations

These elapsed times cover each fresh command, including its subprocesses.
EOF
python3 - "$tmp_dir" >> "$tmp" <<'PYTIMINGS'
import json
from pathlib import Path
import sys
for path in sorted(Path(sys.argv[1]).glob('*.timing.json')):
    phase = json.loads(path.read_text())
    print(f"- {phase['label']}: {phase['duration_seconds']:.3f} seconds")
PYTIMINGS

# Publication compares the complete source/package/toolchain identity with the
# pre-gate snapshot. A concurrent source change preserves logs but rejects the
# receipt. Full outputs and timings are retained append-only, beyond this summary.
python3 scripts/verification_receipts.py publish \
  --before "$tmp_dir/source-before.json" --status "$tmp" --phase-dir "$tmp_dir"
