#!/usr/bin/env sh
set -eu

root_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$root_dir"

out="CURRENT_STATUS.md"
tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/poincare-status.$$-XXXXXX")
tmp="$tmp_dir/CURRENT_STATUS.md"
generated_at=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
toolchain=$(tr -d '\n' < lean-toolchain)

cleanup() {
  rm -rf "$tmp_dir"
}

trap cleanup EXIT

run_capture() {
  label=$1
  shift
  output_file="$tmp_dir/${label}.out"
  status_file="$tmp_dir/${label}.status"

  set +e
  "$@" > "$output_file" 2>&1
  status=$?
  set -e

  printf '%s\n' "$status" > "$status_file"
}

run_capture build lake build
build_status=$(cat "$tmp_dir/build.status")

run_capture interface sh scripts/interface_audit.sh
interface_status=$(cat "$tmp_dir/interface.status")

run_capture mathlib sh scripts/mathlib_gap_audit.sh
mathlib_status=$(cat "$tmp_dir/mathlib.status")

run_capture semantic sh scripts/semantic_surface_audit.sh
semantic_status=$(cat "$tmp_dir/semantic.status")

run_capture root_import sh scripts/root_import_audit.sh
root_import_status=$(cat "$tmp_dir/root_import.status")

run_capture axiom sh scripts/axiom_audit.sh
axiom_status=$(cat "$tmp_dir/axiom.status")

run_capture completion sh scripts/completion_audit.sh
completion_status=$(cat "$tmp_dir/completion.status")

completion_result="not achieved"
if rg -q '^COMPLETION: achieved$' "$tmp_dir/completion.out"; then
  completion_result="achieved"
fi

cat > "$tmp" <<EOF
# Current Poincare Formalization Status

This file is generated by \`scripts/write_status_summary.sh\`.

## Result

- Completion: ${completion_result}
- Generated at: ${generated_at}
- Lean toolchain: ${toolchain}
- Build status: ${build_status}
- Interface audit status: ${interface_status}
- Mathlib gap audit status: ${mathlib_status}
- Semantic surface audit status: ${semantic_status}
- Root import audit status: ${root_import_status}
- Axiom footprint audit status: ${axiom_status}
- Completion audit status: ${completion_status}
EOF

write_section() {
  title=$1
  output_file=$2

  cat >> "$tmp" <<EOF

## ${title}

\`\`\`text
EOF
  cat "$output_file" >> "$tmp"
  cat >> "$tmp" <<EOF
\`\`\`
EOF
}

write_section "Build" "$tmp_dir/build.out"
write_section "Interface Audit" "$tmp_dir/interface.out"
write_section "Mathlib Gap Audit" "$tmp_dir/mathlib.out"
write_section "Semantic Surface Audit" "$tmp_dir/semantic.out"
write_section "Root Import Audit" "$tmp_dir/root_import.out"
write_section "Axiom Footprint Audit" "$tmp_dir/axiom.out"
write_section "Completion Audit" "$tmp_dir/completion.out"

mv "$tmp" "$out"
tmp=""
echo "Wrote $out"
