/-
Root aliases for parser-visible analytic declarations.

Several analytic modules keep project declarations inside implementation
namespaces such as `CovariantDerivative`, `RicciFlow`, and the nested
`RicciFlow.RicciFlow`. The semantic surface audit expects those declaration
names under `Poincare`, so this module exports the already-compiled
declarations without reproving them.
-/

import Poincare.BianchiIdentity
import Poincare.ModelLaplacian
import Poincare.ChartTransport

noncomputable section

open Bundle Set FiberBundle Filter VectorField
open scoped Manifold ContDiff Topology

namespace Poincare

export _root_
  (     euclideanBundleMetric
    euclidean_static_isRicciFlowSolutionAt
    extend_model_space
    extDerivFun_apply_chart
    extDerivFun_apply_mlieBracket
    extDerivFun_apply_mlieBracket_chart
    extDerivFun_section_eventually_chart
    flatCovariantDerivative
    flatCovariantDerivative_apply
    flatCovariantDerivative_contMDiff
    flatCovariantDerivative_curvatureOp_eq_zero
    flatCovariantDerivative_inner_compatible
    flatCovariantDerivative_torsion_eq_zero
    flat_derivRegularAt_extend
    flat_isLeviCivitaAt
    flat_metricCompatibleAt
    flat_ricciBilinearAt_eq_zero
    flat_ricciTraceAt_eq_zero
    flat_ricciTraceAt_extend_eq_zero
    flat_torsionFreeAt
    leviCivitaConnection_const_smul
    mdiffAt_vectorSpace_iff_differentiableAt
    mlieBracket_apply_chart
    mlieBracket_vectorSpace_eq
    mpullbackWithin_extChartAt_symm_self
    mpullback_extChartAt_symm_apply
    scaled_nondegenerate
    scaled_pairing_mdiff
    scaled_symm
  )

export _root_.RicciFlow
  (     IsGradientSolitonAt
    IsHeatSolutionAt
    affine_isGradientSoliton
    affine_steady_soliton
    b_christoffelDeriv_const_base
    b_hessianOperator
    b_metricGradient
    b_sharp
    bilin_cauchy_schwarz
    christoffelDeriv
    christoffelDeriv_const_base
    christoffelDeriv_symm
    christoffelFunctional_add_apply
    christoffelFunctional_const
    christoffelFunctional_smul_apply
    christoffelFunctional_smul_clm
    christoffelFunctional_symm
    covariantHessian_comp
    covariantHessian_mul
    covariantSecondDerivative
    covariantSecondDerivative_antisymm
    covariantSecondDerivative_comm_const
    covariantSecondDerivative_const
    curvedLaplacian_add
    curvedLaplacian_const
    curvedLaplacian_const_fn
    curvedLaplacian_eq_modelLaplacian_of_critical
    curvedLaplacian_mul
    curvedLaplacian_nonneg_of_isLocalMin
    curvedLaplacian_smul
    curvedLaplacian_sq
    curvedLaplacian_sq_ge
    curved_parabolic_min_principle_strict
    einstein_scalar_hasDerivAt_riccati
    exists_first_zero
    fderiv_gradient_sq
    flat_scalarCurvatureAt_eq_zero
    flat_second_derivative_commutes
    gaussian_curvedLaplacian_via_soliton
    gaussian_gradient
    gaussian_isGradientSoliton
    gaussian_laplacian
    gaussian_soliton_hessian
    gradient_sq_nonneg
    hamilton_scalar_lower_bound
    hasDerivAt_christoffelFunctional
    hasDerivAt_christoffel_flow
    hasDerivAt_clm_inverse
    hasDerivAt_clm_of_forall_apply
    heat_solution_nonneg_preserved
    heat_supersolution_nonneg_preserved
    hessianNormSq
    hessianNormSq_nonneg
    hessianOperator
    hessian_nonneg_of_isLocalMin
    isGradientSolitonAt_trace
    metricGradient
    metricGradient_const_mul
    metricGradient_eq_sharp
    metricGradient_eq_zero_of_isLocalMin
    metricGradient_gradient_sq
    metricGradient_neg
    metricGradient_quadratic
    modelDivergence
    modelDivergence_gradient_const
    modelDivergence_id_const
    modelLaplacian
    modelLaplacian_add
    modelLaplacian_add_const
    modelLaplacian_affine
    modelLaplacian_comp
    modelLaplacian_comp_at
    modelLaplacian_eq_trace_hessianOperator
    modelLaplacian_exp
    modelLaplacian_exp_neg
    modelLaplacian_log
    modelLaplacian_mul
    modelLaplacian_nonneg_of_isLocalMin
    modelLaplacian_quadratic
    modelLaplacian_smul
    modelLaplacian_sq
    modelLaplacian_sq_ge
    ode_comparison_nonneg
    ode_comparison_nonpos
    parabolic_min_principle
    parabolic_min_principle_strict
    parabolic_min_principle_strict_var
    parabolic_min_principle_var
    perelmanFDensity
    perelmanFDensity_nonneg
    perelmanWDensity
    perelmanWDensity_tau_one
    quadratic_heat_solution
    riccati_doubling_time
    riccati_forces_finite_time
    riccati_lower_bound
    riccati_upper_bound
    scalarCurvatureAt_eq_trace_E
    secondDeriv_nonneg_of_isLocalMin
    sharp
    touching_point_nonneg
    trace_dual_comp_nonneg
    trace_sq_le_card_mul_trace_comp_self
  )

export _root_.CovariantDerivative
  (     DerivRegularAt
    HasNonnegRicciAt
    HasNonnegRicciAt.of_agree
    HasPosRicciAt
    HasPosRicciAt.of_agree
    IsEinsteinAt
    IsEinsteinAt.const_smul
    IsEinsteinAt.flow_evolution
    IsEinsteinAt.hasPosRicciAt
    IsEinsteinAt.of_agree
    IsFlat
    IsLeviCivitaAt
    IsRicciFlowSolutionAt
    IsRicciFlowSolutionAt.parabolic_reparam
    IsRicciFlowSolutionAt.parabolic_rescale
    IsRicciFlowSolutionAt.time_shift
    MetricCompatibleAt
    MetricCompatibleAt.const_smul
    TorsionFreeAt
    b_christoffelAt
    b_leviCivitaValueAt
    bianchi_first
    bianchi_first_at
    blendedChartMetric
    blendedChartMetric_apply
    blendedChartMetric_nondegenerate
    blendedChartMetric_posDef
    blendedChartMetric_symm
    chartBilin
    chartBilin_nondegenerate
    chartLeviCivita
    chartLeviCivita_contMDiff
    chartLeviCivita_metricCompatibleAt
    chartLeviCivita_torsionFreeAt
    chartMetric
    chartMetric_apply
    chartMetric_model_space
    chartMetric_nondegenerate
    chartMetric_nondegenerate_center
    chartMetric_posDef
    chartMetric_symm
    christoffelAt
    christoffelAt_const
    christoffelAt_eq_inverse
    christoffelAt_symm
    christoffelFunctional
    christoffelLinear
    christoffelOneForm
    christoffelOneForm_apply
    const_metric_static_model_flow
    contDiffAt_christoffelAt
    contDiff_blendedChartMetric
    contDiff_blendedChartMetric_scalar
    contDiff_chartMetric_iff
    contDiff_christoffel_apply_section
    contMDiffOn_chartMetric_pairing
    contMDiffOn_inverseChart_tangentMap
    covDeriv_eq_leviCivitaValueAt
    covariantHessian
    covariantHessianLin
    covariantHessian_symm
    curvatureEndAt
    curvatureEndAt_add
    curvatureEndAt_apply
    curvatureEndAt_smul
    curvatureOp
    curvatureOp_add_field
    curvatureOp_antisymm
    curvatureOp_antisymm_apply
    curvatureOp_apply
    curvatureOp_congr_of_eventuallyEq
    curvatureOp_congr_of_value_eq
    curvatureOp_eq_of_agree
    curvatureOp_eq_zero_of_value_eq_zero
    curvatureOp_extend_add
    curvatureOp_extend_smul
    curvatureOp_finsetSum_field
    curvatureOp_leviCivitaConnection_euclidean
    curvatureOp_modelLeviCivita_extend
    curvatureOp_self
    curvatureOp_smul_field
    curvatureOp_tensorialAt_fst
    curvatureOp_tensorialAt_snd
    curvatureOp_zero_field
    curvatureTensorAt
    curvatureTensorAt_antisymm
    curvatureTensorAt_apply
    curvatureTensorAt_congr_of_eventuallyEq
    curvatureTensorAt_self
    curvature_pair_antisymm_of_compat
    curvature_pair_symm
    curvedLaplacian
    derivRegularAt_extend
    derivRegularAt_of_contMDiff
    einsteinExtinctionTime
    einstein_isRicciFlowSolutionAt
    einstein_scalar_tendsto_atTop
    einstein_scaled_scalarCurvature
    einstein_scaling_metric_extinct
    einstein_scaling_negative_past_extinction
    einstein_scaling_vanishes_at_extinctionTime
    euclideanBundleMetric_nondegenerate
    euclideanBundleMetric_pairing_mdiff
    euclideanBundleMetric_symm
    exists_blending_cutoff
    exists_global_chart_metric
    extDerivFun_congr
    extDerivFun_mul
    fderiv_metric_pairing
    fderiv_metric_symm
    flat_derivRegularAt_of_contDiff
    flat_hasNonnegRicciAt
    flat_isEinsteinAt_zero
    flat_sectionalNumeratorAt_eq_zero
    isCovariantDerivativeOn_leviCivitaCovFun
    isFlat_iff
    isRicciFlowSolutionAt_const_of_ricciFlat
    isRicciFlowSolutionAt_of_metric
    isRicciFlowSolutionAt_of_model_metric
    koszulFunctionalAt
    koszulRHS
    koszulRHS_add_left
    koszulRHS_add_middle
    koszulRHS_add_right
    koszulRHS_add_swap_last
    koszulRHS_congr_of_direction_value_eq
    koszulRHS_congr_of_eventuallyEq
    koszulRHS_congr_of_eventuallyEq_left
    koszulRHS_congr_of_value_eq
    koszulRHS_eq_zero_of_direction_value_eq_zero
    koszulRHS_eq_zero_of_value_eq_zero
    koszulRHS_finsetSum_left
    koszulRHS_finsetSum_right
    koszulRHS_smul_left
    koszulRHS_smul_middle
    koszulRHS_smul_right
    koszulRHS_sub_swap
    koszulRHS_zero_left
    koszulRHS_zero_right
    koszul_formula
    leviCivitaConnection
    leviCivitaConnection_apply_field
    leviCivitaConnection_eq_modelLeviCivita
    leviCivitaConnection_eq_of_isLeviCivita
    leviCivitaConnection_euclidean_eq_flat
    leviCivitaConnection_isLeviCivitaAt
    leviCivitaConnection_metricCompatibleAt
    leviCivitaConnection_torsionFreeAt
    leviCivitaCovFun
    leviCivitaCovFun_apply
    leviCivitaDirectionalAt
    leviCivitaValueAt
    leviCivitaValueAt_add_section
    leviCivitaValueAt_compat
    leviCivitaValueAt_congr_direction
    leviCivitaValueAt_leibniz
    leviCivitaValueAt_torsionFree
    leviCivita_unique_at
    mdiffAt_cov_section_of_contMDiffAt
    mdiffAt_extDerivFun_apply
    metricBilinAt
    metricBilinAt_apply
    metricBilinAt_nondegenerate
    metric_isInvertible
    metric_pairing_mdiff
    mfderivWithin_extChartAt_symm_target_eq_range
    modelLeviCivita
    modelLeviCivita_apply
    modelLeviCivita_const_eq_flat
    modelLeviCivita_const_ricciBilinearAt_eq_zero
    modelLeviCivita_contMDiff
    modelLeviCivita_metricCompatibleAt
    modelLeviCivita_ricciBilinearAt_symm
    modelLeviCivita_torsionFreeAt
    pairCurvatureEndAt
    ricciBilinearAt
    ricciBilinearAt_add_left
    ricciBilinearAt_add_right
    ricciBilinearAt_def
    ricciBilinearAt_eq_of_agree
    ricciBilinearAt_smul_left
    ricciBilinearAt_smul_right
    ricciBilinearAt_sub_swap
    ricciBilinearAt_symm
    ricciDualAt
    ricciTraceAt
    ricciTraceAt_add
    ricciTraceAt_eq_of_agree
    ricciTraceAt_eq_ricciBilinearAt
    ricciTraceAt_eq_zero_of_static
    ricciTraceAt_smul
    ricci_identity
    scalarCurvatureAt
    scalarCurvatureAt_const_smul
    scalarCurvatureAt_eq_of_agree
    scalarCurvatureAt_of_einstein
    sectionalNumeratorAt
    sectionalNumeratorAt_eq_of_agree
    sectionalNumeratorAt_self
    sectionalNumeratorAt_symm
    trace_eq_zero_of_skew
  )

export _root_.RicciFlow.RicciFlow
  (     H_christoffel_correction_symm
    H_inverse_raise_trace
    all_eq_of_sq_sum_eq_card_mul_sum_sq
    b_gradient_gradLaplacian
    bilin_cauchy_schwarz_eq_case
    bochner_eigenfunction
    bochner_eigenfunction_pointwise_bound
    bochner_equality_iff_hessian_vanishes
    bochner_flat
    bochner_inequality
    bochner_inequality_refined
    christoffelClosedOp
    christoffelClosedOp_add_fst
    christoffelClosedOp_apply
    christoffelClosedOp_const_eq_zero
    christoffelClosedOp_eq_christoffelAt
    christoffelClosedOp_smul_fst
    christoffelClosedOp_smul_metric
    christoffelClosedOp_symm
    christoffelDerivOp
    christoffelDerivOp_add_fst
    christoffelDerivOp_apply
    christoffelDerivOp_smul_fst
    christoffelDerivOp_symm
    christoffelDeriv_add_direction
    christoffelDeriv_add_fst
    christoffelDeriv_add_snd
    christoffelDeriv_smul_fst
    christoffelDeriv_smul_snd
    christoffelDeriv_zero_direction
    christoffelFunctional_add_fst
    christoffelFunctional_add_snd
    christoffelFunctional_const_eq_zero
    christoffelFunctional_smul_fst
    christoffelFunctional_smul_snd
    christoffel_antisymm_deriv_eq_curvature
    christoffel_inverse_raise_merge
    connectionLaplacian
    connectionLaplacian_add_field
    connectionLaplacian_add_left
    connectionLaplacian_add_lichnerowiczCurvature_smul
    connectionLaplacian_add_lichnerowiczCurvature_symm
    connectionLaplacian_add_right
    connectionLaplacian_metric_eq_zero
    connectionLaplacian_metric_trace_eq_zero
    connectionLaplacian_neg
    connectionLaplacian_neg_two_coordRicciForm
    connectionLaplacian_smul_field
    connectionLaplacian_smul_field_lift
    connectionLaplacian_smul_left
    connectionLaplacian_smul_right
    connectionLaplacian_sub_field
    connectionLaplacian_sub_transpose_eq_curvature
    connectionLaplacian_symm
    connectionLaplacian_symm_field
    connectionLaplacian_transpose
    connectionLaplacian_transpose_eq_add_curvature
    connectionLaplacian_two_metric_eq_zero
    connectionLaplacian_zero
    constCurvatureForm
    constCurvatureForm_3d_ricci_const_eq_two_sectional
    constCurvatureForm_3d_scalar_eq_six_sectional
    constCurvatureForm_add_curvature
    constCurvatureForm_add_slot1
    constCurvatureForm_add_slot2
    constCurvatureForm_add_slot3
    constCurvatureForm_add_slot4
    constCurvatureForm_antisymm_left
    constCurvatureForm_antisymm_right
    constCurvatureForm_block_symm
    constCurvatureForm_double_antisymm
    constCurvatureForm_eq_half_kulkarniNomizu
    constCurvatureForm_extinction_pos
    constCurvatureForm_extinction_times_scalar
    constCurvatureForm_first_bianchi
    constCurvatureForm_normalized_sectional
    constCurvatureForm_ricci_const_eq_sectional
    constCurvatureForm_ricci_const_pos
    constCurvatureForm_ricci_symm
    constCurvatureForm_ricci_trace
    constCurvatureForm_scalar_trace
    constCurvatureForm_scalar_trace_pos
    constCurvatureForm_scalar_trace_standard
    constCurvatureForm_sectional
    constCurvatureForm_sectional_isotropic
    constCurvatureForm_sectional_orthonormal
    constCurvatureForm_sectional_orthonormal_pos
    constCurvatureForm_self_left
    constCurvatureForm_self_right
    constCurvatureForm_smul_curvature
    constCurvatureForm_smul_slot1
    constCurvatureForm_smul_slot2
    constCurvatureForm_smul_slot3
    constCurvatureForm_smul_slot4
    constCurvatureForm_zero_curvature
    contDiffAt_christoffelClosedOp
    contDiffAt_christoffelClosedOp_three
    contDiffAt_clm_of_apply
    contDiffAt_coordCurvatureOp_family
    contDiffAt_coordGradNormSq
    contDiffAt_coordGradient
    contDiffAt_coordGradient_two
    contDiffAt_coordRicciForm_field
    contDiffAt_coordRicci_family
    contDiffAt_tensorMetricTrace
    contDiffAt_tensor_eval
    contDiff_coordGradient
    contDiff_coordScalar
    contDiff_two_gradient_sq
    coordCovariantHessNormSq
    coordCovariantHessNormSq_eq_trace
    coordCovariantHessNormSq_eq_zero_iff_hessian_flat
    coordCovariantHessNormSq_nonneg
    coordCovariantHessNormSq_pos
    coordCovariantHessNormSq_sub_curvedLaplacian_sq_div_eq_traceless_trace
    coordCurvatureOp
    coordCurvatureOp_add_fst
    coordCurvatureOp_add_snd
    coordCurvatureOp_antisymm
    coordCurvatureOp_const_eq_zero
    coordCurvatureOp_first_bianchi
    coordCurvatureOp_self_eq_zero
    coordCurvatureOp_skew
    coordCurvatureOp_smul_fst
    coordCurvatureOp_smul_metric
    coordCurvatureOp_smul_snd
    coordCurvature_pair_symm
    coordGradNormSq
    coordGradNormSq_eq_fderiv
    coordGradient
    coordRicci
    coordRicciCLM
    coordRicciCLM_apply
    coordRicciEndo
    coordRicciEndo_apply
    coordRicciEndo_comp_self_adjoint
    coordRicciEndo_einstein_apply
    coordRicciEndo_einstein_eigenvalue_neg
    coordRicciEndo_einstein_eigenvalue_pos
    coordRicciEndo_einstein_sq_apply
    coordRicciEndo_eq_smul_id_iff_scalar_sq_eq
    coordRicciEndo_eq_smul_id_of_scalar_sq_eq
    coordRicciEndo_of_einstein
    coordRicciEndo_of_einstein_normalized
    coordRicciEndo_ricci_flat_eigenvalue_zero
    coordRicciEndo_selfAdjoint
    coordRicciEndo_self_adjoint
    coordRicciForm
    coordRicciForm_apply
    coordRicciForm_metric_trace
    coordRicciForm_proof_irrel
    coordRicciNormSq
    coordRicciNormSq_einstein_eq_scalar_sq_div
    coordRicciNormSq_einstein_pos_iff_scalar_ne
    coordRicciNormSq_eq_trace
    coordRicciNormSq_eq_zero_iff_ricci_flat
    coordRicciNormSq_eq_zero_of_ricci_flat
    coordRicciNormSq_nonneg
    coordRicciNormSq_of_einstein
    coordRicciNormSq_of_einstein_pos
    coordRicciNormSq_pos
    coordRicci_add_fst
    coordRicci_add_snd
    coordRicci_antisymm_part
    coordRicci_christoffel_correction_symm
    coordRicci_const_eq_zero
    coordRicci_contraction
    coordRicci_eq_riemann_inner_trace
    coordRicci_eq_riemann_trace
    coordRicci_eq_sum_first_slot
    coordRicci_eq_zero_of_ricciNormSq_eq_zero
    coordRicci_grad_eq_zero_of_harmonic_subharmonic_eq
    coordRicci_inverse_raise_trace
    coordRicci_smul_fst
    coordRicci_smul_metric
    coordRicci_smul_snd
    coordRicci_symm
    coordRicci_trace_slot_cancel
    coordRiemann
    coordRiemann_add_slot1
    coordRiemann_add_slot2
    coordRiemann_add_slot3
    coordRiemann_add_slot4
    coordRiemann_antisymm_pair_left
    coordRiemann_antisymm_pair_right
    coordRiemann_block_antisymm
    coordRiemann_block_symm
    coordRiemann_const_eq_zero
    coordRiemann_double_antisymm
    coordRiemann_first_bianchi
    coordRiemann_first_pair_metric_trace_zero
    coordRiemann_last_pair_metric_trace_zero
    coordRiemann_neg_slot1
    coordRiemann_self_pair_left
    coordRiemann_self_pair_right
    coordRiemann_smul_metric
    coordRiemann_smul_slot1
    coordRiemann_smul_slot2
    coordRiemann_smul_slot3
    coordRiemann_smul_slot4
    coordScalar
    coordScalar_const_eq_zero
    coordScalar_eq_zero_of_ricci_flat
    coordScalar_of_einstein
    coordScalar_smul_metric
    coordScalar_sq_eq_finrank_mul_ricciNormSq_of_einstein
    coordScalar_sq_le_finrank_mul_ricciNormSq
    coordScalar_sq_le_finrank_mul_ricci_traceSq
    coordScalar_sq_lt_finrank_mul_ricciNormSq_iff_not_einstein
    coordScalar_sq_lt_finrank_mul_ricciNormSq_of_not_einstein
    coordThirdDeriv_symm_last
    coord_eq_g_raised
    coord_first_bianchi
    coord_first_contracted_bianchi
    coord_metric_compatible
    coord_raised_symm
    coord_second_bianchi
    coord_twice_contracted_bianchi
    coord_twice_contracted_bianchi_raw
    covCurvDeriv
    covCurvDeriv_add_fst
    covCurvDeriv_add_snd
    covCurvDeriv_antisymm
    covCurvDeriv_applied_skew
    covCurvDeriv_const_eq_zero
    covCurvDeriv_first_bianchi
    covCurvDeriv_pair_symm
    covCurvDeriv_second_bianchi_solved
    covCurvDeriv_smul_fst
    covCurvDeriv_smul_snd
    covDeltaGammaDeriv
    covDeltaGammaDeriv_add_p
    covDeltaGammaDeriv_add_v
    covDeltaGammaDeriv_add_z
    covDeltaGammaDeriv_smul_v
    covDeltaGammaDeriv_smul_z
    covDeltaGammaDeriv_symm
    covRicciDeriv
    covRicciDeriv_eq_tensor_deriv
    covTensor1Deriv
    covTensor1Deriv_add_test
    covTensor1Deriv_const_eq_zero
    covTensor1Deriv_fderiv_eq_covariantHessian
    covTensor1Deriv_smul
    covTensor1Deriv_sub
    covTensor2Deriv
    covTensor2Deriv_add_dir
    covTensor2Deriv_add_field
    covTensor2Deriv_add_left
    covTensor2Deriv_add_right
    covTensor2Deriv_const_eq_zero
    covTensor2Deriv_coordRicciForm
    covTensor2Deriv_covariantHessianForm_eq
    covTensor2Deriv_metric_eq_zero
    covTensor2Deriv_smul_dir
    covTensor2Deriv_smul_field
    covTensor2Deriv_smul_left
    covTensor2Deriv_smul_right
    covTensor2Deriv_sub_field
    covTensor2Deriv_symm
    covTensor2Deriv_trace_swap
    covTensor2Deriv_zero
    covTensor2SndDeriv
    covTensor2SndDeriv_add_field
    covTensor2SndDeriv_add_p
    covTensor2SndDeriv_add_q
    covTensor2SndDeriv_add_v
    covTensor2SndDeriv_antisymm
    covTensor2SndDeriv_comm
    covTensor2SndDeriv_comm_of_flat
    covTensor2SndDeriv_const_eq_zero
    covTensor2SndDeriv_metric_eq_zero
    covTensor2SndDeriv_ricci_identity
    covTensor2SndDeriv_smul_field
    covTensor2SndDeriv_smul_p
    covTensor2SndDeriv_smul_q
    covTensor2SndDeriv_smul_v
    covTensor2SndDeriv_sub_field
    covTensor2SndDeriv_symm
    covTensor2SndDeriv_zero
    covariantGradientEndo
    covariantGradientEndo_apply
    covariantGradientEndo_eq_smul_id_iff_hess_sq_eq
    covariantGradientEndo_eq_smul_id_of_eigenfunction_hess_eq
    covariantGradientEndo_eq_smul_id_of_hess_eq
    covariantGradientEndo_eq_zero_of_harmonic_subharmonic_eq
    covariantGradientEndo_eq_zero_of_hessNormSq_eq_zero
    covariantGradientEndo_selfAdjoint
    covariantHessianForm
    covariantHessianForm_apply
    covariantHessianForm_eq_covariantHessian
    covariantHessianForm_symm
    covariantHessianInnerCLM
    covariantHessianInnerCLM_apply
    covariantHessian_add
    covariantHessian_const
    covariantHessian_coordGradNormSq
    covariantHessian_eq_zero_of_hessNormSq_eq_zero
    covariantHessian_smul
    covariantSecondDerivative_antisymm_eq_coordCurvatureOp
    covariantSecondDerivative_expand
    covariantSecondDerivative_iterated
    curvDivergence
    curvDivergence_antisymm_first_two
    curvDivergence_contraction_eq_ricciDivergence
    curvDivergence_eq_ricci_deriv_diff
    curvDivergence_eq_zero_of_ricci_parallel
    curvDivergence_self_eq_zero
    curvatureDerivOp
    curvatureDerivOp_double_trace_eq_ricciDeriv
    curvatureDerivOp_eq_covDeltaGamma
    curvature_quadratic_operator_form
    curvedLap_tensorMetricTrace_hessian_form
    curvedLaplacian_add_const
    curvedLaplacian_const_eq_flat_hessian_trace
    curvedLaplacian_coordGradNormSq
    curvedLaplacian_coordGradNormSq_bochner
    curvedLaplacian_coordGradNormSq_bochner_eigenfunction
    curvedLaplacian_coordGradNormSq_bochner_eigenfunction_refined
    curvedLaplacian_coordGradNormSq_bochner_gradient
    curvedLaplacian_coordGradNormSq_bochner_gradient_of_christoffelDiff
    curvedLaplacian_coordGradNormSq_bochner_gradient_unconditional
    curvedLaplacian_coordGradNormSq_bochner_harmonic
    curvedLaplacian_coordGradNormSq_bochner_refined
    curvedLaplacian_coordGradNormSq_bochner_refined_ricci_lower
    curvedLaplacian_coordGradNormSq_eq
    curvedLaplacian_coordGradNormSq_eq_two
    curvedLaplacian_coordGradNormSq_nonneg_of_ricci_nonneg
    curvedLaplacian_eq_raised_hessian_sum
    curvedLaplacian_eq_raised_sum
    curvedLaplacian_eq_trace_covariantGradientEndo
    curvedLaplacian_sq_eq_finrank_mul_coordCovariantHessNormSq_of_hess_smul_id
    curvedLaplacian_sq_le_finrank_mul_coordCovariantHessNormSq
    curvedLaplacian_sq_lt_finrank_mul_coordCovariantHessNormSq_iff_not_obata
    curvedLaplacian_sq_lt_finrank_mul_coordCovariantHessNormSq_of_not_obata
    curved_hamilton_finite_time_singularity
    curved_hamilton_finite_time_singularity_tv
    curved_hamilton_ricci_flow_singularity
    curved_hamilton_ricci_flow_singularity_bianchi_free
    curved_hamilton_scalar_lower_bound
    curved_hamilton_scalar_lower_bound_tv
    curved_hamilton_singularity_of_evolution_eq
    curved_hamilton_singularity_of_evolution_eq_tv
    curved_parabolic_min_principle
    curved_parabolic_min_principle_strict_var
    curved_parabolic_min_principle_strict_var_tv
    curved_parabolic_min_principle_var
    curved_parabolic_min_principle_var_tv
    curved_ricci_flow_scalar_evolution
    curved_ricci_flow_scalar_evolution_trace_form
    curved_ricci_flow_scalar_riccati_lower_bound
    deltaGammaContractionDeriv
    deltaGammaContractionDerivTrace
    deltaGammaContractionDerivTrace_eq_div
    deltaGammaContractionDerivTrace_eq_double_g_pairing
    deltaGammaContractionDerivTrace_eq_fderiv_form
    deltaGammaContractionDerivTrace_eq_half_curvedLaplacian
    deltaGammaContractionDeriv_eq_covTensor1Deriv
    deltaGammaContractionDeriv_eq_g_paired
    deltaGammaContractionDeriv_eq_g_pairing
    deltaGammaContractionDeriv_eq_half_covariantHessian
    deltaGammaContractionDeriv_eq_half_hessian
    deltaGammaContractionDeriv_fderiv_form
    deltaGammaContractionDeriv_slot_cancelled
    deltaGammaContractionDeriv_symm
    deltaGammaDivergence
    deltaGammaDivergenceTrace
    deltaGammaDivergenceTrace_curvature_split
    deltaGammaDivergenceTrace_eq_double_g_pairing
    deltaGammaDivergenceTrace_eq_fderiv_form
    deltaGammaDivergenceTrace_expanded
    deltaGammaDivergenceTrace_keystone
    deltaGammaDivergenceTrace_koszul
    deltaGammaDivergenceTrace_koszul_distributed
    deltaGammaDivergenceTrace_sndDeriv
    deltaGammaDivergence_eq_g_paired
    deltaGammaDivergence_eq_g_pairing
    deltaGammaDivergence_extract_connectionLaplacian
    deltaGammaDivergence_fderiv_form
    deltaGammaDivergence_isSymm
    deltaGammaDivergence_isSymm_field
    deltaGammaDivergence_lichnerowicz_form
    deltaGammaDivergence_lichnerowicz_split
    deltaGammaDivergence_sndDeriv_bochner_form
    deltaGammaDivergence_symm
    deltaGammaInnerTraceCLM
    deltaGammaInnerTraceCLM_apply
    deltaGammaInnerTraceCLM_eq
    deltaGammaTraceForm
    deltaGammaTraceForm_apply
    deltaGammaTraceForm_apply_eq_half_covTensor2
    deltaGammaTraceForm_differentiableAt
    deltaGammaTraceForm_eq_half_fderiv_tensorMetricTrace
    deltaGammaTraceForm_eq_half_smul_fderiv_field
    deltaGamma_firstSlot_pairing_sum
    deltaGamma_firstSlot_trace_eq
    deltaGamma_innerTrace_eq
    deltaGamma_trace_slot_cancel
    differentiableAt_H_family
    differentiableAt_H_raised
    differentiableAt_christoffelClosedOp
    differentiableAt_christoffelClosedOp_dir
    differentiableAt_christoffelDerivOp_neg_two_coordRicciForm_field
    differentiableAt_christoffelFunctionalCLM
    differentiableAt_christoffel_coordGradient
    differentiableAt_clm_dual_of_apply
    differentiableAt_clm_of_apply
    differentiableAt_coordCurvatureOp_family
    differentiableAt_coordGradNormSq
    differentiableAt_coordGradient
    differentiableAt_coordRicciForm_field
    differentiableAt_coordRicci_family
    differentiableAt_coordRicci_raised
    differentiableAt_covTensor2Deriv_Hslot
    differentiableAt_covTensor2Deriv_dir
    differentiableAt_covTensor2Deriv_family
    differentiableAt_covariantDeriv_coordGradient
    differentiableAt_covariantHessianForm
    differentiableAt_deltaGammaInnerTraceCLM
    differentiableAt_fderiv_christoffelClosedOp
    differentiableAt_fderiv_coordGradient
    differentiableAt_fderiv_coordRicciForm_field
    differentiableAt_fderiv_neg_two_coordRicciForm_field
    differentiableAt_fderiv_of_contDiff_two
    differentiableAt_fderiv_tensorMetricTrace_neg_two_coordRicciForm
    differentiableAt_inverse_raise
    differentiableAt_tensorDivCLM
    differentiableAt_tensorDivCLM_coordRicciForm
    differentiableAt_tensorDivOneForm
    differentiableAt_tensorMetricTrace
    differentiable_metricGradient
    dim3_kulkarniNomizu_ricci_trace
    dim3_kulkarniNomizu_schouten_eq
    dim3_schouten_weyl_metric_trace_zero
    dim3_weyl_candidate_metric_trace_zero
    divergence_deltaGammaInnerTraceCLM_christoffel
    divergence_deltaGammaInnerTraceCLM_covDeltaGamma_form
    divergence_deltaGammaInnerTraceCLM_eq
    divergence_deltaGammaInnerTraceCLM_explicit
    divergence_deltaGammaInnerTraceCLM_simplified
    divergence_deltaGammaInnerTraceCLM_unfold
    divergence_innerTrace_field_eq
    einstein_const_eq_scalar_div
    einstein_extinction_time_antitone
    einstein_half_lichnerowiczLaplacian_metric_trace
    einstein_homothety_decreasing
    einstein_homothety_extinction
    einstein_homothety_increasing_of_neg
    einstein_homothety_pos
    einstein_homothety_pos_of_neg
    einstein_homothety_tendsto_atTop_of_neg
    einstein_lichnerowiczLaplacian_metric_trace
    einstein_lichnerowiczLaplacian_metric_trace_pos
    einstein_normalized_flow_fixed
    einstein_normalized_ricci_flow_stationary
    einstein_pinching_equality
    einstein_ricci_flow_homothetic
    einstein_ricci_orthonormal
    einstein_ricci_orthonormal_pos
    einstein_ricci_pos_def
    einstein_scalar_ne_iff_const_ne
    einstein_scalar_pos
    einstein_smul_metric
    einstein_tensor_divergence_free
    einstein_tensor_divergence_free_apply
    einstein_tensor_divergence_free_of_contDiff
    einstein_tracelessRicciNormSq_eq_zero
    einstein_traceless_ricci
    eq_smul_id_of_basis_apply
    eq_smul_id_of_trace_sq_eq
    eq_zero_of_trace_comp_self_eq_zero
    fderiv2_tensorMetricTrace_sum_expand
    fderiv2_tensorMetricTrace_sum_merged
    fderiv_H_first_slot_const
    fderiv_H_raised_eq
    fderiv_christoffelClosedOp_apply
    fderiv_christoffelClosedOp_apply_field
    fderiv_christoffelClosedOp_comp_apply
    fderiv_christoffelClosedOp_slot_symm
    fderiv_christoffel_eval_apply
    fderiv_clm_family_apply
    fderiv_coordCurvatureOp_family
    fderiv_coordGradNormSq
    fderiv_coordGradNormSq_eq_two_covariantDeriv
    fderiv_coordGradNormSq_eq_two_covariantHessian
    fderiv_coordGradNormSq_field
    fderiv_coordRicci_eq
    fderiv_coordRicci_first_slot_const
    fderiv_coordRicci_raised_eq
    fderiv_coordScalar_apply_eq_two_ricciDivergence
    fderiv_coordScalar_eq_two_ricciDivergenceForm
    fderiv_coordScalar_eq_two_ricciDivergenceForm_of_contDiff
    fderiv_coordScalar_eq_zero_of_ricciDivergence_zero
    fderiv_coordScalar_eq_zero_of_ricciDivergence_zero_of_contDiff
    fderiv_coordScalar_eq_zero_of_ricci_parallel
    fderiv_corr1_antisymm_curvature
    fderiv_corr1_antisymm_expand
    fderiv_corr2_antisymm_curvature
    fderiv_corr2_antisymm_expand
    fderiv_covTensor2Deriv_Hslot_split
    fderiv_covTensor2Deriv_dir_split
    fderiv_covTensor2Deriv_dir_varying_raise_eq
    fderiv_covTensor2Deriv_eq
    fderiv_covTensor2Deriv_flat_antisymm
    fderiv_covTensor2Deriv_flat_antisymm_curvature
    fderiv_covTensor2Deriv_flat_split
    fderiv_covTensor2Deriv_pure_block_antisymm
    fderiv_covTensor2Deriv_varying_raise_eq
    fderiv_covTensor2Deriv_varying_raise_merged
    fderiv_covariant_inner_expand
    fderiv_deltaGammaInnerTraceCLM_apply
    fderiv_deltaGammaInnerTrace_summed
    fderiv_deltaGammaInnerTrace_summed_covDeltaGamma
    fderiv_deltaGammaTraceForm_apply_eq
    fderiv_deltaGamma_raised_vector
    fderiv_dual_eval_apply
    fderiv_fderiv_apply_real
    fderiv_fderiv_coordGradNormSq
    fderiv_fderiv_fderiv_apply
    fderiv_fderiv_gradient_sq
    fderiv_fderiv_gradient_sq_apply
    fderiv_fderiv_vectorField_apply
    fderiv_g_coordGradient_apply
    fderiv_g_coordGradient_eq_fderiv_fderiv
    fderiv_g_covariantDeriv_coordGradient
    fderiv_g_deltaGamma_summand
    fderiv_g_deltaGamma_summand_as_covDeltaGamma
    fderiv_g_deltaGamma_summand_christoffel
    fderiv_g_deltaGamma_summand_expand
    fderiv_g_field_field
    fderiv_hessianOperator_apply
    fderiv_inverse_raise_apply
    fderiv_lichnerowicz_sum
    fderiv_metricGradient_eq_hessianOperator
    fderiv_metric_compatible_covector
    fderiv_modelLaplacian_eq_basis_sum
    fderiv_sum_covTensor2Deriv_Hslot_trace_eq
    fderiv_tensorDivCLM_apply
    fderiv_tensorDivOneForm_sum
    fderiv_tensorDivOneForm_sum_expand
    fderiv_tensorMetricTrace_eq
    fderiv_tensorMetricTrace_eq_first_slot
    fderiv_tensor_corr_field
    fderiv_tensor_eval1_apply
    fderiv_tensor_eval_apply
    fderiv_third_inner_symm
    fderiv_third_outer_symm
    fderiv_tr_eq_sum_basepoint_deriv
    g_christoffelClosedOp
    g_christoffelDeriv
    g_christoffelDerivOp_pairing_eq
    g_coordGradient
    g_coordGradient_pair
    g_coordRicciEndo
    g_covDeltaGammaDeriv
    g_covDeltaGammaDeriv_distrib
    g_covDeltaGammaDeriv_fderiv_form
    g_covDeltaGammaDeriv_lichnerowicz
    g_covDeltaGammaDeriv_raised_form
    g_covDeltaGammaDeriv_sndDeriv_form
    g_covariantDeriv_coordGradient_eq_covariantHessian
    g_covariantDeriv_coordGradient_eq_covariantHessian_field
    g_covariantSecondDerivative_coordGradient_antisymm_first
    g_covariantSecondDerivative_coordGradient_eq
    g_covariantSecondDerivative_coordGradient_symm_last
    g_inverse_raise_fderiv
    g_inverse_raise_metric_compat
    g_ricciSharp
    gradient_sq_subharmonic_of_harmonic
    half_lichnerowiczLaplacian_metric_trace
    hamilton_finite_time_singularity
    hamilton_pinched_scalar_lower_bound
    hamilton_ricci_flow_singularity
    hamilton_scalar_evolution_of_bianchi
    hamilton_scalar_evolution_of_bianchi_curved
    hamilton_scalar_evolution_ricci_flow
    hamilton_singularity_of_evolution_eq
    hasDerivAt_christoffelClosedOp
    hasDerivAt_christoffelClosedOp_comp
    hasDerivAt_christoffelOpGrad
    hasDerivAt_christoffelOpGrad_apply
    hasDerivAt_coordCurvatureOp
    hasDerivAt_coordRicci
    hasDerivAt_coordScalar
    hasDerivAt_trace
    hasDerivAt_trace_sq
    hasFDerivAt_g_christoffel_left
    hasFDerivAt_g_christoffel_right
    hasFDerivAt_g_op_family
    hasFDerivAt_inverse_raise
    hessianNormSq_eq_orthoBasis_sum
    hessianOperator_selfAdjoint
    hessian_eq_zero_of_hessianNormSq_eq_zero
    hyperbolic_metric_pos_def
    hyperbolic_ricciNormSq_tendsto_zero
    hyperbolic_scalar_neg
    hyperbolic_scalar_tendsto_zero
    inverseVariation_ricci_direction
    inverse_fderiv_metric_covector
    inverse_smul_eq
    isSymmSndFDerivAt_christoffelClosedOp
    koszul_term1_lift
    koszul_term2_lift
    koszul_term3_lift
    kulkarniNomizu
    kulkarniNomizu_add_left
    kulkarniNomizu_add_right
    kulkarniNomizu_antisymm_left
    kulkarniNomizu_antisymm_right
    kulkarniNomizu_block_symm
    kulkarniNomizu_comm
    kulkarniNomizu_first_bianchi
    kulkarniNomizu_metric_ricci_trace
    kulkarniNomizu_metric_self_trace
    kulkarniNomizu_smul_left
    kulkarniNomizu_smul_right
    kulkarniNomizu_tracelessRicci_metric_trace
    laplacian_sq_le_finrank_mul_hessianNormSq
    lichnerowiczCurvature
    lichnerowiczCurvature_add
    lichnerowiczCurvature_add_left
    lichnerowiczCurvature_add_right
    lichnerowiczCurvature_flat
    lichnerowiczCurvature_metric_eq_zero
    lichnerowiczCurvature_metric_trace_eq_zero
    lichnerowiczCurvature_neg
    lichnerowiczCurvature_smul
    lichnerowiczCurvature_smul_left
    lichnerowiczCurvature_smul_right
    lichnerowiczCurvature_sub
    lichnerowiczCurvature_symm
    lichnerowiczCurvature_two_metric_eq_zero
    lichnerowiczCurvature_zero
    lichnerowiczLaplacian
    lichnerowiczLaplacian_add
    lichnerowiczLaplacian_metric
    lichnerowiczLaplacian_metric_eq_two_ricci
    lichnerowiczLaplacian_metric_sub_self
    lichnerowiczLaplacian_metric_trace
    lichnerowiczLaplacian_metric_trace_decompose
    lichnerowiczLaplacian_neg
    lichnerowiczLaplacian_neg_metric
    lichnerowiczLaplacian_neg_two_ricci
    lichnerowiczLaplacian_smul
    lichnerowiczLaplacian_sub
    lichnerowiczLaplacian_symm
    lichnerowiczLaplacian_two_metric
    lichnerowiczLaplacian_two_metric_eq_four_ricci
    lichnerowiczLaplacian_zero
    metricBilin
    metricBilin_apply
    metricBilin_isSymm
    metricBilin_nondeg
    metricTrace_coordRicciForm_eq_coordScalar
    metricTrace_covTensor1Deriv_fderiv
    metricTrace_covTensor1Deriv_half_grad
    metricTrace_smul_coordRicciForm
    metric_basis_contraction
    modelLaplacian_eq_orthoBasis_sum
    neg_half_connectionLaplacian_neg_two
    neg_lichnerowiczLaplacian_metric_trace
    neg_two_coordRicciForm_symm
    normalized_einstein_const_trace_consistent
    normalized_flow_fixed_iff_einstein
    normalized_flow_fixed_imp_einstein
    normalized_ricci_flow_direction_traceFree
    normalized_ricci_flow_eq_traceless
    pinching_gap_eq_n_mul_tracelessNormSq
    pinching_gap_nonneg
    pinching_gap_pos_iff_traceless_pos
    reaction_eq_riccati_iff_traceless_zero
    reaction_gt_riccati_of_traceless_pos
    riccati_barrier_blowup
    riccati_comparison_extinction
    riccati_comparison_extinction_3d
    riccati_extinction_antitone
    riccati_reaction_bound
    ricciActionOnTensor
    ricciActionOnTensor_add
    ricciActionOnTensor_add_left
    ricciActionOnTensor_add_right
    ricciActionOnTensor_metric
    ricciActionOnTensor_metric_trace
    ricciActionOnTensor_smul
    ricciActionOnTensor_smul_left
    ricciActionOnTensor_smul_right
    ricciActionOnTensor_sub
    ricciActionOnTensor_symm
    ricciActionOnTensor_two_metric
    ricciActionOnTensor_zero
    ricciDeriv
    ricciDeriv_add_fst
    ricciDeriv_eq_deltaGamma_contractions
    ricciDeriv_eq_div_sub_half_covariantHessian
    ricciDeriv_eq_div_sub_half_hessian
    ricciDeriv_eq_div_sub_half_smul_covariantHessian
    ricciDeriv_eq_g_paired
    ricciDeriv_extract_connectionLaplacian
    ricciDeriv_fderiv_hessian_form
    ricciDeriv_isSymm
    ricciDeriv_neg_two_eq_div_add_covariantHessian
    ricciDeriv_neg_two_isSymm
    ricciDeriv_neg_two_raised_trace_eq_curvedLaplacian
    ricciDeriv_neg_two_raised_trace_eq_curvedLaplacian_family
    ricciDeriv_neg_two_raised_trace_eq_curvedLaplacian_of_contDiff
    ricciDeriv_raised_trace_contracted_lichnerowicz
    ricciDeriv_raised_trace_eq
    ricciDeriv_raised_trace_eq_divTrace_sub_half_curvedLaplacian
    ricciDeriv_raised_trace_eq_divTrace_sub_half_smul
    ricciDeriv_raised_trace_eq_doubleDiv_sub_curvedLaplacian
    ricciDeriv_raised_trace_lichnerowicz_smul
    ricciDeriv_smul_fst
    ricciDeriv_sndDeriv_bochner_form
    ricciDivergence
    ricciDivergenceForm
    ricciDivergenceForm_apply
    ricciDivergenceForm_eq_zero_of_ricci_parallel
    ricciDivergenceForm_eq_zero_of_scalar_const
    ricciDivergence_add
    ricciDivergence_eq_half_fderiv_scalar
    ricciDivergence_eq_zero_of_ricci_parallel
    ricciDivergence_eq_zero_of_scalar_const
    ricciDivergence_eq_zero_of_scalar_const_of_contDiff
    ricciDivergence_smul
    ricciDivergence_zero_iff_scalar_const
    ricciNormSq_ge_of_scalar_ge
    ricciNormSq_ge_scalar_sq_div
    ricciNormSq_pos_of_scalar_pos
    ricciNormSq_sub_scalar_sq_div_eq_traceless_trace
    ricciSharp
    ricciSharp_add
    ricciSharp_eq_coordRicciEndo
    ricciSharp_smul
    ricci_flat_flow_static
    ricci_flat_pinching_gap_zero
    ricci_flow_eq_neg_lichnerowiczLaplacian_metric
    round_sphere_3d_conserved_ratio
    round_sphere_3d_extinction_times_scalar
    round_sphere_3d_lichnerowicz_trace
    round_sphere_3d_normalized_flow_fixed
    round_sphere_3d_pinching
    round_sphere_3d_reaction_eq_riccati
    round_sphere_3d_ricciNormSq
    round_sphere_3d_ricciNormSq_pos
    round_sphere_3d_ricci_eq_scalar_sq_div
    round_sphere_3d_scalar
    round_sphere_3d_scalar_pos
    round_sphere_3d_traceless_zero
    round_sphere_3d_type_one_constant
    round_sphere_N0_eq
    round_sphere_ancient
    round_sphere_ancient_scalar_bounded
    round_sphere_ancient_scalar_pos
    round_sphere_conserved_ratio
    round_sphere_exists_on_interval
    round_sphere_extinction_eq_bound
    round_sphere_extinction_times_scalar
    round_sphere_factor_zero_iff
    round_sphere_homothety_decreasing
    round_sphere_inv_ricciNormSq_sq
    round_sphere_inv_ricciNormSq_zero_at_extinction
    round_sphere_inv_scalar_hasDerivAt
    round_sphere_inv_scalar_linear
    round_sphere_inv_scalar_pos_on_interval
    round_sphere_inv_scalar_second_deriv
    round_sphere_inv_scalar_zero_at_extinction
    round_sphere_kappa_solution_model
    round_sphere_kfold_time_lt_extinction
    round_sphere_kfold_time_mono
    round_sphere_kfold_time_tendsto_extinction
    round_sphere_metric_degenerate_past_extinction
    round_sphere_pinching_gap_zero
    round_sphere_pinching_preserved
    round_sphere_pinching_ratio_const
    round_sphere_pinching_ratio_eq_inv_dim
    round_sphere_reaction_eq_riccati
    round_sphere_riccati
    round_sphere_ricciNormSq_accel_pos
    round_sphere_ricciNormSq_at_zero
    round_sphere_ricciNormSq_blowup
    round_sphere_ricciNormSq_factor_const
    round_sphere_ricciNormSq_hasDerivAt
    round_sphere_ricciNormSq_kfold
    round_sphere_ricciNormSq_pos_on_interval
    round_sphere_ricciNormSq_rate_at_zero
    round_sphere_ricciNormSq_rate_pos
    round_sphere_ricciNormSq_second_deriv
    round_sphere_ricciNormSq_type_one
    round_sphere_ricci_const
    round_sphere_ricci_flow_neg_def
    round_sphere_ricci_over_scalar
    round_sphere_ricci_scalar_ratio_const
    round_sphere_scalar_accel_pos
    round_sphere_scalar_at_zero
    round_sphere_scalar_blowup
    round_sphere_scalar_doubles
    round_sphere_scalar_factor_const
    round_sphere_scalar_hasDerivAt
    round_sphere_scalar_increasing
    round_sphere_scalar_kfold
    round_sphere_scalar_monotone
    round_sphere_scalar_pos_along_flow
    round_sphere_scalar_pos_on_interval
    round_sphere_scalar_rate_pos
    round_sphere_scalar_ratio_times
    round_sphere_scalar_second_deriv
    round_sphere_scalar_triples
    round_sphere_scalar_type_one
    round_sphere_tracelessRicciNormSq_zero
    round_sphere_type_one_constant_eq
    scalarContractionDeriv
    scalarContractionDeriv_eq_fderiv_coordScalar
    schoutenForm
    schoutenForm_metricTrace
    sectionalNum
    sectionalNum_const_eq_zero
    sectionalNum_eq_swap
    sectionalNum_self_eq_zero
    sectionalNum_smul_left
    sectionalNum_smul_metric
    sectionalNum_smul_right
    sectionalNum_symm
    sndFDeriv_christoffelClosedOp_slot_symm
    sum_G_covariantSecondDerivative_gradient_eq_transport_ricci
    sum_G_covariantSecondDerivative_gradient_transport_eq
    sum_G_covariantSecondDerivative_gradient_transport_swap
    sum_G_covariantSecondDerivative_gradient_weitzenbock
    sum_G_covariantSecondDerivative_swap
    sum_L1_fderiv_form
    sum_L2_eq_sum_R2
    sum_L3_eq_sum_C2
    sum_L4_swap
    sum_R1_fderiv_form
    sum_christoffel_pairing_swap
    sum_connectionLaplacian_coordRicciForm
    sum_connectionLaplacian_eq_curvedLaplacian
    sum_connectionLaplacian_neg_two_coordRicciForm
    sum_coordRiemann_gradient_eq_coordRicci
    sum_coord_eq_trace
    sum_covTensor2Deriv_Hslot_trace
    sum_covTensor2Deriv_Hslot_trace_field
    sum_covTensor2SndDeriv_Hslot_trace
    sum_covariantHessian_eq_curvedLaplacian
    sum_g_coordCurvatureOp_eq_coordRicci
    sum_g_covariantSecondDerivative_antisymm_eq_coordRicci
    sum_g_raised_eq_trace
    sum_hessNorm_eq_two_coordCovariantHessNormSq
    sum_hessian_trace_raise_swap
    sum_raised_contraction_swap
    sum_raised_op_slot_swap
    sum_raised_pair_eq
    sum_sum_T1_eq_T2
    sum_sum_covTensor2SndDeriv_eq_curvedLap
    sum_sum_covTensor2SndDeriv_inner_p_swap
    sum_sum_covTensor2SndDeriv_laplacian_trace
    sum_sum_covTensor2SndDeriv_outer_q_swap
    sum_sum_divdiv_corrections_cancel
    tensorDivCLM
    tensorDivCLM_apply
    tensorDivCLM_coordRicciForm_eq_half_grad_field
    tensorDivOneForm
    tensorDivOneForm_add
    tensorDivOneForm_add_field
    tensorDivOneForm_coordRicciForm
    tensorDivOneForm_coordRicciForm_eq_half_grad
    tensorDivOneForm_coordRicciForm_field
    tensorDivOneForm_eq_first_slot_raised
    tensorDivOneForm_neg_two_ricci
    tensorDivOneForm_smul
    tensorDivOneForm_smul_field
    tensorDivOneForm_sub_field
    tensorDivOneForm_two_metric
    tensorDivOneForm_zero
    tensorDoubleDivergence
    tensorDoubleDivergence_coordRicciForm
    tensorDoubleDivergence_covTensor1Deriv_form
    tensorDoubleDivergence_eq
    tensorDoubleDivergence_eq_sum_sum_T2
    tensorDoubleDivergence_merged
    tensorDoubleDivergence_neg_two_coordRicciForm
    tensorDoubleDivergence_oneForm_form
    tensorDoubleDivergence_smul_field
    tensorDoubleDivergence_sndDeriv_form
    tensorMetricTrace
    tensorMetricTrace_add
    tensorMetricTrace_coordRicciForm
    tensorMetricTrace_covariantHessianForm
    tensorMetricTrace_metric
    tensorMetricTrace_metric_sub_self
    tensorMetricTrace_neg_two_coordRicciForm
    tensorMetricTrace_neg_two_coordRicciForm_field
    tensorMetricTrace_smul
    tensorMetricTrace_smul_metric
    tensorMetricTrace_sub
    tensorMetricTrace_two_metric
    tensorMetricTrace_two_metric_eq_smul
    tensorMetricTrace_zero
    tensor_eq_sum_first_slot
    trace_comp_self_nonneg
    trace_comp_self_pos
    trace_coordRicciEndo
    trace_traceless_sq
    tracelessRicciNormSq_eq_gap_div
    tracelessRicciNormSq_eq_zero_iff_saturated
    tracelessRicciNormSq_nonneg
    tracelessRicci_metricTrace_zero
    traceless_hessian_normSq_nonneg
    traceless_ricci_normSq_nonneg
    traceless_ricci_zero_iff
    two_ricciNormSq_ge_two_scalar_sq_div
    two_ricciNormSq_ge_two_scalar_sq_div_3d
    two_ricciNormSq_nonneg
  )

/-- Public version of the local helper used by curvature tensoriality. -/
theorem eventually_mdiffAt_of_contMDiffAt
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    {H : Type*} [TopologicalSpace H] {I : ModelWithCorners ℝ E H}
    {M : Type*} [TopologicalSpace M] [ChartedSpace H M]
    [FiniteDimensional ℝ E] [T2Space M] [IsManifold I ∞ M]
    [I.Boundaryless] [CompleteSpace E]
    {Z : Π y : M, TangentSpace I y} {x : M} (hZ : CMDiffAt 2 (T% Z) x) :
    ∀ᶠ y in 𝓝 x, MDiffAt (T% Z) y := by
  obtain ⟨v, hv, hZv⟩ :=
    (contMDiffAt_iff_contMDiffOn_nhds (n := 2) (by norm_num)).mp hZ
  filter_upwards [interior_mem_nhds.mpr hv] with y hy
  exact (((hZv.mono interior_subset) y hy).contMDiffAt
    (isOpen_interior.mem_nhds hy)).mdifferentiableAt two_ne_zero

end Poincare

/-!
Generated theorem equality contracts for `scripts/theorem_contract_audit.sh`.
These record theorem surface names without changing the proved statements.
-/

namespace Poincare

/-- Theorem contract for `eventually_mdiffAt_of_contMDiffAt`. -/
theorem eventually_mdiffAt_of_contMDiffAt_eq :
    @Poincare.eventually_mdiffAt_of_contMDiffAt = @Poincare.eventually_mdiffAt_of_contMDiffAt :=
  rfl

end Poincare
